# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, b'New'), (1, b'Active'), (2, b'Unactive')], default=0),
        ),
    ]
