# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_available',
            field=models.IntegerField(default=0),
        ),
    ]
